name: Microservice Emprunt Retour CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Donner les permissions d'exécution au script Maven Wrapper
      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      # Étape 3 : Configurer Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: ./mvnw dependency:resolve

      # Étape 5 : Lancer les tests
      - name: Run tests
        run: ./mvnw test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ghalimyassine3 }}
          password: ${{ secrets.b_P4j-qhe4Zd2uh}}

      # Étape 3 : Configurer Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Étape 4 : Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/emprunt-retour:latest
